<?php 
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?> 
<li class="parent shopping-bag-item">
	<a class="cart-contents" href="#">
		<i class="fa fa-exchange"></i>
							<span class="labels"><?php echo $this->__('Compare') ?></span>	
			<?php if($_helper->getItemCount() > 0): ?>
			<span class="amount"> 
			    <span><?php echo $_helper->getItemCount() ?></span>	
			</span>
			<?php endif ?>
		
	</a>
	<ul class="sub-menu">
		<li>
			<div class="shopping-bag">
				<div class="bag-contents">
				<?php if($_helper->getItemCount() > 0): ?>
			        <ol id="compare-items">
			        <?php foreach($_items as $_index => $_item): ?>
			            <li class="item">
			                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
			                <a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a>
			                <a data-id="<?php echo $_item->getId() ?>" href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove') ?>" class="btn-compare-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"><i class="icon-cancel-circle"></i></a>
			            </li>
			        <?php endforeach; ?>
			        </ol>
			        <script type="text/javascript">decorateList('compare-items')</script>
				</div>          
				<div class="bag-buttons">
					<button type="button" title="<?php echo $this->__('Compare') ?>" class="button" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')">
                <span><span><?php echo $this->__('Compare') ?></span></span>
            </button>
					 <a class="btn-clear-all-compare" href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');">
                <?php echo $this->__('Clear All') ?>
            </a> 
				</div>
			    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
    <?php endif; ?>
			</div>
		</li>
	</ul>	            
</li>
